sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t saleem8054/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true saleem8054/react-test npm run test

after_success:
  - docker build -t saleem8054/multi-client ./client
  - docker build -t saleem8054/multi-nginx ./nginx
  - docker build -t saleem8054/multi-server ./server
  - docker build -t saleem8054/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push saleem8054/multi-client
  - docker push saleem8054/multi-nginx
  - docker push saleem8054/multi-server
  - docker push saleem8054/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-847340557883
  bucket_path: multi-docker
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY